# Generated by Django 4.2.7 on 2023-11-26 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teetime',
            name='players',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teetime',
            name='time',
            field=models.TimeField(),
        ),
    ]
